name: Delete Windows prereleases related to deleted branch
on:
  delete

jobs:
  delete_release:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Delete non-master branch release
      uses: author/action-rollback@stable
      with:
        tag: ${{ steps.extract_branch.outputs.branch }}
        always_delete_tag: true
