name: Publish docker image
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    # Only on a tagged release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and publish
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: cohort-extractor
        push_git_tag: true
