name: Tests

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Run test suite
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start SQL Server and Presto instances for the tests
      run: docker-compose up -d mssql presto
    - name: Run actual tests
      run: PYTHONPATH=. pytest tests/
  test_model:
    runs-on: ubuntu-latest
    name: Test stata can run against the actual model, using dummy data
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -e .
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.opensafely.org
        username: docker
        password: ${{ secrets.OPENSAFELY_DOCKER_PASSWORD }}
    - name: Run model
      run: cohortextractor run dummy test_stata expectations
  test-package-build:
    runs-on: ubuntu-latest
    name: Test we can build PyPI package
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install wheel package
      run: |
        pip install wheel
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
